### ISSUE TITLE
Build a browser/desktop client 

### ISSUE THREAD

**Issue by Tratcher** [Tratcher/FindIt#6]
I want to be able to do the following on my computer:
- Log in, view, and edit my list(s). This would exclude the GPS tagging of completed items.
- View a map of nearby items from my list. Use a larger default scale than the mobile app.
- Plan directions to one or more destinations to get items. Send these to my device?
- Discover other items available in a particular location.
- Account management
- Get company/service information and support

Admins:
- Explore data
- Manage users

**Comment by nikolenkoanton92** [comment]
@Tratcher I will love to help you with this.

**Comment by Tratcher** [comment]
Up for using ASP.NET Core 2.0? It will be out soon.

I'm not sure how to tie the authentication parts back into the Azure Mobile Apps auth we set up, that will take some research.
The list management and maps stuff should be a port of the mobile app logic we already have. Most of the other stuff may get added to the mobile apps eventually too.

**Comment by Tratcher** [comment]
This issue was moved to Tratcher/FindItBrowser#1
